CREATE TABLE contact_tags
(
    contact_id BIGINT NOT NULL,
    tag_id     BIGINT NOT NULL,
    CONSTRAINT pk_contact_tags PRIMARY KEY (contact_id, tag_id)
);

CREATE TABLE contacts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    first_name      VARCHAR(255)                            NOT NULL,
    last_name       VARCHAR(255)                            NOT NULL,
    email           VARCHAR(255)                            NOT NULL,
    phone           VARCHAR(255),
    company         VARCHAR(255),
    "group"         VARCHAR(255),
    status          VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_contacts PRIMARY KEY (id)
);

ALTER TABLE contacts
    ADD CONSTRAINT uc_contacts_email UNIQUE (email);

ALTER TABLE contact_tags
    ADD CONSTRAINT fk_contag_on_contact FOREIGN KEY (contact_id) REFERENCES contacts (id);

ALTER TABLE contact_tags
    ADD CONSTRAINT fk_contag_on_tag FOREIGN KEY (tag_id) REFERENCES tags (id);