spring:
  application:
    name: campaign-management-system
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DATASOURCE_URL:jdbc:postgresql://localhost:5433/myDb?createDatabaseIfNotExist=true}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:client_id.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET:"Google_client_secret"}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    uri: /api-docs
    operations-sorter: method

logging:
  level:
    root: WARN
  file:
    name: app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:custom_jwt_secret_key}
    expiration-time: 3600000

    refresh-token:
      expiration-time: 360000000

server:
  port: 9000